name: Jacob D. Moses
tagline: Postdoctoral Researcher, History of Science, Technology & Medicine
markdown: kramdown
theme: jekyll-theme-primer
twitter:
  username: jacobdmoses
  card: summary
url: jdmoses.com
sass:
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
google_analytics: G-EHX8HX5WZG
permalink: /:basename/
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/jacob-moses-preview.jpg